#include "win32_window.h"
#include <windowsx.h>
namespace { const wchar_t kWindowClassName[] = L"FLUTTER_RUNNER_WIN32_WINDOW"; int g_class_registration_count = 0;
class WindowClassRegistrar { public: ~WindowClassRegistrar(){ if(window_class_) UnregisterClass(kWindowClassName,nullptr); }
 const wchar_t* GetWindowClass(){ if(!window_class_){ WNDCLASS wc{}; wc.hCursor=LoadCursor(nullptr,IDC_ARROW); wc.lpszClassName=kWindowClassName; wc.style=CS_HREDRAW|CS_VREDRAW; wc.cbClsExtra=0; wc.cbWndExtra=0; wc.hInstance=GetModuleHandle(nullptr); wc.hIcon=LoadIcon(nullptr,IDI_APPLICATION); wc.hbrBackground=0; wc.lpszMenuName=nullptr; wc.lpfnWndProc=Win32Window::WndProc; RegisterClass(&wc); window_class_=kWindowClassName;} return window_class_; } private: const wchar_t* window_class_=nullptr;};
WindowClassRegistrar* GetWindowClassRegistrar(){ static WindowClassRegistrar registrar; return &registrar; }}
Win32Window::Win32Window(){++g_class_registration_count;} Win32Window::~Win32Window(){--g_class_registration_count; DestroyWindow(window_handle_);}
bool Win32Window::Create(const std::wstring& title,const Point& origin,const Size& size){ DestroyWindow(window_handle_); const wchar_t* window_class=GetWindowClassRegistrar()->GetWindowClass(); HWND window=CreateWindow(window_class,title.c_str(),WS_OVERLAPPEDWINDOW,(int)origin.x,(int)origin.y,(int)size.width,(int)size.height,nullptr,nullptr,GetModuleHandle(nullptr),this); if(!window) return false; return OnCreate(); }
bool Win32Window::Show(){ return ShowWindow(window_handle_,SW_SHOWNORMAL); } HWND Win32Window::GetHandle(){return window_handle_;}
void Win32Window::SetChildContent(HWND content){ child_content_=content; SetParent(content,window_handle_); RECT frame=GetClientArea(); MoveWindow(content,frame.left,frame.top,frame.right-frame.left,frame.bottom-frame.top,true); SetFocus(child_content_); }
RECT Win32Window::GetClientArea(){ RECT frame; GetClientRect(window_handle_,&frame); return frame; } void Win32Window::SetQuitOnClose(bool v){quit_on_close_=v;}
bool Win32Window::OnCreate(){return true;} void Win32Window::OnDestroy(){}
LRESULT Win32Window::MessageHandler(HWND hwnd,UINT message,WPARAM wparam,LPARAM lparam) noexcept { switch(message){ case WM_DESTROY: window_handle_=nullptr; OnDestroy(); if(quit_on_close_) PostQuitMessage(0); return 0; case WM_SIZE: if(child_content_) MoveWindow(child_content_,0,0,LOWORD(lparam),HIWORD(lparam),TRUE); return 0; case WM_ACTIVATE: if(child_content_) SetFocus(child_content_); return 0; } return DefWindowProc(hwnd,message,wparam,lparam); }
Win32Window* Win32Window::GetThisFromHandle(HWND const window) noexcept { return reinterpret_cast<Win32Window*>(GetWindowLongPtr(window,GWLP_USERDATA)); }
LRESULT CALLBACK Win32Window::WndProc(HWND const window,UINT const message,WPARAM const wparam,LPARAM const lparam) noexcept { if(message==WM_NCCREATE){ auto window_struct=reinterpret_cast<CREATESTRUCT*>(lparam); SetWindowLongPtr(window,GWLP_USERDATA,reinterpret_cast<LONG_PTR>(window_struct->lpCreateParams)); auto that=static_cast<Win32Window*>(window_struct->lpCreateParams); that->window_handle_=window; } else if(auto that=GetThisFromHandle(window)){ return that->MessageHandler(window,message,wparam,lparam); } return DefWindowProc(window,message,wparam,lparam); }
