-- EduGestion 360 - Modelo academico inicial
-- Proyecto Supabase nuevo. No depende del esquema historico.

begin;

create schema if not exists private;

create table public.perfil_usuario (
  id uuid primary key references auth.users(id) on delete cascade,
  correo varchar(150) not null unique,
  nombres varchar(100) not null,
  apellidos varchar(100) not null,
  ci varchar(30) not null unique,
  telefono varchar(30),
  rol varchar(20) not null,
  estado boolean not null default true,
  fecha_registro timestamptz not null default now(),
  constraint perfil_usuario_rol_check
    check (rol in ('ADMINISTRADOR', 'DOCENTE')),
  constraint perfil_usuario_correo_check
    check (btrim(correo) <> ''),
  constraint perfil_usuario_nombres_check
    check (btrim(nombres) <> ''),
  constraint perfil_usuario_apellidos_check
    check (btrim(apellidos) <> ''),
  constraint perfil_usuario_ci_check
    check (btrim(ci) <> '')
);

create table public.estudiante (
  id_estudiante bigint generated by default as identity primary key,
  codigo varchar(30) unique,
  nombres varchar(100) not null,
  apellidos varchar(100) not null,
  ci varchar(30) not null unique,
  telefono varchar(30),
  estado boolean not null default true,
  fecha_registro timestamptz not null default now(),
  constraint estudiante_codigo_check
    check (codigo is null or btrim(codigo) <> ''),
  constraint estudiante_nombres_check
    check (btrim(nombres) <> ''),
  constraint estudiante_apellidos_check
    check (btrim(apellidos) <> ''),
  constraint estudiante_ci_check
    check (btrim(ci) <> '')
);

create table public.asignatura (
  id_asignatura bigint generated by default as identity primary key,
  codigo varchar(30) not null unique,
  nombre varchar(150) not null,
  descripcion varchar(300),
  estado boolean not null default true,
  fecha_registro timestamptz not null default now(),
  constraint asignatura_codigo_check
    check (btrim(codigo) <> ''),
  constraint asignatura_nombre_check
    check (btrim(nombre) <> '')
);

create table public.periodo_academico (
  id_periodo bigint generated by default as identity primary key,
  nombre varchar(100) not null unique,
  fecha_inicio date not null,
  fecha_fin date not null,
  estado boolean not null default true,
  constraint periodo_academico_nombre_check
    check (btrim(nombre) <> ''),
  constraint periodo_academico_fechas_check
    check (fecha_fin >= fecha_inicio)
);

create table public.inscripcion (
  id_inscripcion bigint generated by default as identity primary key,
  estudiante_id bigint not null
    references public.estudiante(id_estudiante) on delete restrict,
  asignatura_id bigint not null
    references public.asignatura(id_asignatura) on delete restrict,
  periodo_id bigint not null
    references public.periodo_academico(id_periodo) on delete restrict,
  fecha_inscripcion date not null default current_date,
  estado boolean not null default true,
  constraint inscripcion_unica
    unique (estudiante_id, asignatura_id, periodo_id)
);

create table public.asignacion_docente (
  id_asignacion bigint generated by default as identity primary key,
  docente_id uuid not null
    references public.perfil_usuario(id) on delete restrict,
  asignatura_id bigint not null
    references public.asignatura(id_asignatura) on delete restrict,
  periodo_id bigint not null
    references public.periodo_academico(id_periodo) on delete restrict,
  fecha_asignacion date not null default current_date,
  estado boolean not null default true,
  constraint asignacion_docente_unica
    unique (docente_id, asignatura_id, periodo_id)
);

create table public.asistencia (
  id_asistencia bigint generated by default as identity primary key,
  inscripcion_id bigint not null
    references public.inscripcion(id_inscripcion) on delete restrict,
  asignacion_docente_id bigint not null
    references public.asignacion_docente(id_asignacion) on delete restrict,
  fecha date not null,
  estado varchar(20) not null,
  observacion varchar(300),
  fecha_registro timestamptz not null default now(),
  constraint asistencia_estado_check
    check (estado in ('PRESENTE', 'AUSENTE', 'LICENCIA')),
  constraint asistencia_unica
    unique (inscripcion_id, asignacion_docente_id, fecha)
);

create table public.calificacion (
  id_calificacion bigint generated by default as identity primary key,
  inscripcion_id bigint not null
    references public.inscripcion(id_inscripcion) on delete restrict,
  asignacion_docente_id bigint not null
    references public.asignacion_docente(id_asignacion) on delete restrict,
  tipo_evaluacion varchar(100),
  nota numeric(5, 2) not null,
  observacion varchar(300),
  fecha_registro timestamptz not null default now(),
  constraint calificacion_nota_check
    check (nota between 0 and 100),
  constraint calificacion_tipo_check
    check (tipo_evaluacion is null or btrim(tipo_evaluacion) <> '')
);

-- Indices de consulta y relaciones.
create index perfil_usuario_rol_estado_idx
  on public.perfil_usuario (rol, estado);
create index estudiante_estado_idx
  on public.estudiante (estado);
create index asignatura_estado_idx
  on public.asignatura (estado);
create index asignatura_nombre_idx
  on public.asignatura (nombre);
create index periodo_academico_estado_idx
  on public.periodo_academico (estado);
create index inscripcion_estudiante_idx
  on public.inscripcion (estudiante_id);
create index inscripcion_asignatura_periodo_idx
  on public.inscripcion (asignatura_id, periodo_id);
create index inscripcion_estado_idx
  on public.inscripcion (estado);
create index asignacion_docente_docente_idx
  on public.asignacion_docente (docente_id);
create index asignacion_docente_asignatura_periodo_idx
  on public.asignacion_docente (asignatura_id, periodo_id);
create index asignacion_docente_estado_idx
  on public.asignacion_docente (estado);
create index asistencia_inscripcion_idx
  on public.asistencia (inscripcion_id);
create index asistencia_asignacion_fecha_idx
  on public.asistencia (asignacion_docente_id, fecha);
create index calificacion_inscripcion_idx
  on public.calificacion (inscripcion_id);
create index calificacion_asignacion_idx
  on public.calificacion (asignacion_docente_id);

-- Una asignacion solo puede pertenecer a un perfil DOCENTE activo.
create or replace function private.validar_perfil_docente()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not exists (
    select 1
    from public.perfil_usuario
    where id = new.docente_id
      and rol = 'DOCENTE'
      and estado = true
  ) then
    raise exception 'El perfil seleccionado no es un docente activo.';
  end if;

  return new;
end;
$$;

create trigger asignacion_docente_validar_perfil
before insert or update
on public.asignacion_docente
for each row
execute function private.validar_perfil_docente();

-- La inscripcion y la asignacion deben corresponder a la misma asignatura
-- y al mismo periodo academico.
create or replace function private.validar_relacion_academica()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_inscripcion public.inscripcion%rowtype;
  v_asignacion public.asignacion_docente%rowtype;
begin
  select * into v_inscripcion
  from public.inscripcion
  where id_inscripcion = new.inscripcion_id;

  select * into v_asignacion
  from public.asignacion_docente
  where id_asignacion = new.asignacion_docente_id;

  if v_inscripcion.id_inscripcion is null
     or v_asignacion.id_asignacion is null
     or v_inscripcion.estado = false
     or v_asignacion.estado = false
     or v_inscripcion.asignatura_id <> v_asignacion.asignatura_id
     or v_inscripcion.periodo_id <> v_asignacion.periodo_id then
    raise exception 'La inscripcion y la asignacion docente no corresponden a la misma asignatura y periodo.';
  end if;

  return new;
end;
$$;

create trigger asistencia_validar_relacion
before insert or update
on public.asistencia
for each row
execute function private.validar_relacion_academica();

create trigger calificacion_validar_relacion
before insert or update
on public.calificacion
for each row
execute function private.validar_relacion_academica();

-- Estas funciones se ejecutan exclusivamente mediante sus triggers.
revoke all on function private.validar_perfil_docente() from public;
revoke all on function private.validar_relacion_academica() from public;
revoke all on schema private from public;

comment on table public.perfil_usuario is
  'Usuarios autenticados del sistema: ADMINISTRADOR o DOCENTE.';
comment on table public.estudiante is
  'Entidad academica sin cuenta en Supabase Auth.';
comment on table public.asignatura is
  'Catalogo de asignaturas con baja logica mediante estado.';

commit;
